### ISSUE TITLE
Twitch

### ISSUE THREAD

**Issue by xDItsTej** [EnderdracheLP/streamer-tools#3]
I have the Streamer Tools set up, but when I go onto Streamlabs OBS, it doesn't update what song i'm playing, time left, etc. Any fix?
![image](https://user-images.githubusercontent.com/97074458/155900956-f46ae8da-adc4-408a-835b-c32a25fcf1dd.png)

**Comment by ComputerElite** [comment]
Ig you haven't entered the ip of your quest correctly

**Comment by michael-r-elp** [comment]
Closing this issue since there hasn't been any response, so I'd consider it resolved.
