### ISSUE TITLE
Song crash on 1.17.1

### ISSUE THREAD

**Issue by AxylisFR** [EnderdracheLP/streamer-tools#4]
So i play on 1.17.1 to stream because it has the mod MRCPlus that i need to have a good image quality but everytime i use streamer-tools, when i launch a song, the game crashes

**Comment by ComputerElite** [comment]
Make sure that you use the right version of Streamer tools (0.2.1). 1.17.1 won't recieve any updates anymore (unless @michael-r-elp wants to do that which I don't think he wants). the latest release shouldn't have those problems.

**Comment by AxylisFR** [comment]
> Make sure that you use the right version of Streamer tools (0.2.1). 1.17.1 won't recieve any updates anymore (unless @michael-r-elp wants to do that which I don't think he wants). the latest release shouldn't have those problems.

I do use the lastest version yes

**Comment by ComputerElite** [comment]
which means that you use the version for 1.21 on 1.17 which won't work

**Comment by michael-r-elp** [comment]
If you're using the correct version for Beat Saber 1.17.1 and are getting crashes try disabling other mods and if possible supply a adb logcat log. 

You can also try asking in the Beat Saber Legacy Group Discord Server inside the #quest-support channel for help about the issue or on how to use adb logcat to get logs.

If they can't help with the issue then I might be able to lead you in the right direction about the cause for the crash you're experiencing, but please understand that I can no longer supply fixes for older versions of the mod.

**Comment by michael-r-elp** [comment]
Closing this issue now, since there haven't been any responses, I assume everything worked out
