### ISSUE TITLE
Wrong image mimetype (image/jpeg)

### ISSUE THREAD

**Issue by fred913** [EnderdracheLP/streamer-tools#6]
According to [https://www.w3.org/Graphics/JPEG/](https://www.w3.org/Graphics/JPEG/) it's `image/jpeg` for jpeg files, and `image/jpg` shouldn't be anywhere, actually.

**Comment by fred913** [comment]
I checked the code and you may add two checks in ServerHTTP.cpp

**Comment by michael-r-elp** [comment]
Thanks for opening an issue about it, I didn't notice the wrong mime type, I've changed it to the correct one now
If you see anything else wrong, feel free to let me know

I'll close the issue now, the fix will be in the next release
