### ISSUE TITLE
[Feature Request] More infomations on Location

### ISSUE THREAD

**Issue by Myzumi** [EnderdracheLP/streamer-tools#7]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

More Numbers listed in the Location property, like being in the main menu, song select, or Playing a map

**Describe alternatives you've considered**

**Additional context**

This is a small request for an Application i'm working that utilities Streamer Tools as a main source of data for the given application, due to lack of infomations where the player is right now, its hard to customize the application based on the location (or i might understand this "location" property wrong, if yes, see it as a feature request)

**Comment by ComputerElite** [comment]
Streamer tools already gives you that data

**Comment by ComputerElite** [comment]
https://github.com/EnderdracheLP/streamer-tools/wiki/DataFormat#-json-format-

**Comment by Myzumi** [comment]
Alright, but seems like its not updating for me, everytime i get the data from Streamer Tools, i only get the location of 0 while i'm playing a map or being in the song selection etc

**Comment by ComputerElite** [comment]
As an example on how to use the data you can look at this code if you want https://github.com/ComputerElite/streamer-tools-client

**Comment by ComputerElite** [comment]
> Alright, but seems like its not updating for me, everytime i get the data from Streamer Tools, i only get the location of 0 while i'm playing a map or being in the song selection etc

Hm I remember that happening but we fixed that. What game version are you running?

**Comment by Myzumi** [comment]
Never mind, i might have overseen it. Thanks anyways for the help!

**Comment by ComputerElite** [comment]
No problem. If you have any other problems or questions feel free to ask here again

**Comment by Myzumi** [comment]
Hi, i'm back to report something small, didnt wanted to open a new issue.

While experimenting with stuff, i've noticed if you select a song and go BACK to the main screen (mode selection), the websocket still sends the selected title, maybe something can be done for this? (it screws a bit with my detection if youre in the song select or main menu)

**Comment by ComputerElite** [comment]
That's intentional and should be handled by the client. An example on how to handle it can be found somewhere here https://github.com/ComputerElite/ComputerElite.github.io/blob/main/tools/Streamer_Tools_Quest_Overlay/pulling.js
